version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: cakephp_app
    ports:
      - "8085:80"
    volumes:
      - ./config/app_local.php:/var/www/html/config/app_local.php:ro
      - ./vendor:/var/www/html/vendor
      - ./logs:/var/www/html/logs
      - ./tmp:/var/www/html/tmp
    environment:
      - DB_HOST=YOUR_DB_HOST
      - DB_PORT=3306
      - DB_NAME=db_ef
      - DB_USER=YOUR_DB_USER
      - DB_PASSWORD=YOUR_DB_PASSWORD
      - DEBUG=true
    restart: unless-stopped
    user: root